[browser]
gatherUsageStats = false

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#76a6bf"

# Background color for the main content area.
#backgroundColor =

# Background color used for the sidebar and most interactive widgets.
#secondaryBackgroundColor =

# Color used for almost all text.
#textColor =

# The font family for all text in the app, except code blocks. One of
# "sans serif", "serif", or "monospace".
# To use a custom font, it needs to be added via [theme.fontFaces]. üê∞ü•ö
#font =

toolbarMode = "auto"